### PR TITLE
Fix has attribute error

### PR DESCRIPTION
**Pull request by yusufali2205**
### Summary
We need to add an additional check on the hasAttribute property on unload. This will check to make sure hasAttribute exists before we use it.

### Additional Details
Closing the application which is embedding a page is throwing error:
`Object doesn't support property or method 'hasAttribute'`
On logging out [this element](https://github.com/cerner/xfc/blob/d424349018ae247aa6eecbcd01c335f67af1b37a/src/provider/application.js#L274) it shows `[object Object]`
image
Which doesn't look like a page element. So we need to add a check in case the variable `element` is not an html element.

[CONTRIBUTORS.md]: ../CONTRIBUTORS.md
[License]: ../LICENSE

### CODE REVIEW

**Comment by yusufali2205** [comment]
@mhemesath please review

**Comment by mhemesath** [comment]
> On logging out this element it shows [object Object]

That's what IE logs out for complex object. Elements **are** objects. With that said, at this point I don't have time to investigate further, and I feel like this PR is just patching a different underlying problem. Based on the code, all objects we call that method on should be objects.

**Comment by yusufali2205** [comment]
> > On logging out this element it shows [object Object]
> 
> That's what IE logs out for complex object. Elements **are** objects. With that said, at this point I don't have time to investigate further, and I feel like this PR is just patching a different underlying problem. Based on the code, all objects we call that method on should be objects.

On doing `alert(document.activeElement)` in IE, I see it logs HTMLBodyElement
image

**Comment by yusufali2205** [comment]
can we get this merged?

**Comment by yusufali2205** [comment]
@NSLockhart @mhemesath can you merge this?

**Pull request merged**
